sudo: required
services:
  - docker

before_install:
  - docker build -t plastico/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true plastico/docker-react npm run test -- --coverage