sudo: required
services:
  - docker

before_install:
  - docker build -t plastico/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true plastico/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-035414502441"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY